### ISSUE TITLE
Carga del sitio actual

### ISSUE THREAD

**Issue by ggsalas** [gulBAC/sitio_v4#1]
Hola @cawaweb ¿Vos vas a subir acá el sitio actual? Para probar un nuevo theme será bueno que este repo tenga la carpeta /wp_content actual y una base de datos para que pueda importar. Otra opción es exportar el actual sitio como xml pero no se si es la mejor opción. En cualquier caso indicame como seguimos.

**Comment by cawaweb** [comment]
Hola! Lo primero que tenemos que ver es el diseño que vamos a hacer. Una vez que tengamos eso definimos como se va a componer el repo. Pienso que al tratarse de un tema para WP por ahí con sólo tener los archivos del tema podemos trabajar sin problemas. Sería poner estos archivos en un ambiente con WP instalado y listo.

Decime si no es así, abrazo!

**Comment by ggsalas** [comment]
Para trabajar en un nuevo diseño me resulta muy conveniente tener toda la
base de datos y plugins de wordpress para poder probar el tema en una
instalación local, por eso si el repo es de /wp-content va a funcionar
mejor.

Respecto a elegir el diseño mi propuesta es trabajar sobre [genesis framework](http://www.studiopress.com/)  Yo tengo el tema [parallax pro](http://my.studiopress.com/themes/parallax/) y creo que va a ir perfecto ya que es simplemente la base, todo se puede modificar.

**Comment by cawaweb** [comment]
Por falta de alguien que administre el sitio y debido a que estuvo caído bastante tiempo decidí volver a algo estatico que no requiera tanto trabajo.
